
export const NEW_APPOINT = 'NEW_APPOINT'
export const NEW_APPOINT_SUCCESS = 'NEW_APPOINT_SUCCESS'

export const CREATE_APPOINT = 'CREATE_APPOINT'
export const CREATE_APPOINT_PENDING = 'CREATE_APPOINT_PENDING'
export const CREATE_APPOINT_SUCCESS = 'CREATE_APPOINT_SUCCESS'
export const CREATE_APPOINT_FAILURE = 'CREATE_APPOINT_FAILURE'

export const LIST_APPOINT = 'LIST_APPOINT'
export const LIST_APPOINT_PENDING = 'LIST_APPOINT_PENDING'
export const LIST_APPOINT_SUCCESS = 'LIST_APPOINT_SUCCESS'
export const LIST_APPOINT_FAILURE = 'LIST_APPOINT_FAILURE'
