
export const NEW_CUSTOMER = 'NEW_CUSTOMER'
export const NEW_CUSTOMER_SUCCESS = 'NEW_CUSTOMER_SUCCESS'

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const CREATE_CUSTOMER_PENDING = 'CREATE_CUSTOMER_PENDING'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'

export const LIST_CUSTOMER = 'LIST_CUSTOMER'
export const LIST_CUSTOMER_PENDING = 'LIST_CUSTOMER_PENDING'
export const LIST_CUSTOMER_SUCCESS = 'LIST_CUSTOMER_SUCCESS'
export const LIST_CUSTOMER_FAILURE = 'LIST_CUSTOMER_FAILURE'
