
export const NEW_DOCTOR = 'NEW_DOCTOR'
export const NEW_DOCTOR_SUCCESS = 'NEW_DOCTOR_SUCCESS'

export const CREATE_DOCTOR = 'CREATE_DOCTOR'
export const CREATE_DOCTOR_PENDING = 'CREATE_DOCTOR_PENDING'
export const CREATE_DOCTOR_SUCCESS = 'CREATE_DOCTOR_SUCCESS'
export const CREATE_DOCTOR_FAILURE = 'CREATE_DOCTOR_FAILURE'

export const LIST_DOCTOR = 'LIST_DOCTOR'
export const LIST_DOCTOR_PENDING = 'LIST_DOCTOR_PENDING'
export const LIST_DOCTOR_SUCCESS = 'LIST_DOCTOR_SUCCESS'
export const LIST_DOCTOR_FAILURE = 'LIST_DOCTOR_FAILURE'
